AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'

Rails:
  Enabled: true

# Disable 'Assignment Branch Condition size for %s is too high. [%.4g/%.4g]'
Metrics/AbcSize:
  Enabled: false

# Disable class length constraints for controllers
Metrics/ClassLength:
  Exclude:
    - 'app/controllers/**/*'

# Disable block length for RSpec tests
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# Maximum method length 15 lines
Metrics/MethodLength:
  Max: 15

# Disable Class definitions using ::
Style/ClassAndModuleChildren:
  Enabled: false

# Disable Missing top-level class documentation comment.
Style/Documentation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/NumericLiterals:
  Enabled: false
